### ISSUE TITLE
Feature:Algorithm Editor

### ISSUE THREAD

**Issue by jackorjorn** [Capnode/Algoloop#1]
May I ask how to write the algorithm in the software, like the algorithm editor, so that you can test the algorithm immediately after writing the algorithm, Thank you!

**Comment by Capnode** [comment]
Today, the algorithms can not be written inside Algoloop. Algorithm in Python can be written with a standard editor and a C# algorithm must be written and compiled with VIsualStudio. After the algorithm is written (and compiled) it can be added to Algoloop in the Strategies tab. There is an example strategy added first time you start Algoloop.

However, if I understand you correctly, you would like to write and run the algorithm within Algoloop?

**Comment by jackorjorn** [comment]
> Today, the algorithms can not be written inside Algoloop. Algorithm in Python can be written with a standard editor and a C# algorithm must be written and compiled with VIsualStudio. After the algorithm is written (and compiled) it can be added to Algoloop in the Strategies tab. There is an example strategy added first time you start Algoloop.
> 
> However, if I understand you correctly, you would like to write and run the algorithm within Algoloop?

Yes, I want to write a strategy editor so that I can edit strategies in the software. ^ _ ^
Only a simple text editor is needed at the beginning.

**Comment by Capnode** [comment]
You are welcome to contribute with a strategy editor to this project.
