### ISSUE TITLE
Common Repository vs Submodule for QuantConnect.Lean

### ISSUE THREAD

**Issue by arakis** [Capnode/Algoloop#8]
What are the reasons to extend QuantConnect.Lean instead of having them as git Submodule / keep them as separate Repository?

Maybe the reasons are to modify the source, but as i see, most of the features have an Interface, you they can extended / cusotmized.

**Comment by Capnode** [comment]
The ideal situation would be to use QuantConnect.Lean as Nuget packages without any need for access to the QuantConnect source code.. However, some changes to QuantConnect.Lean code has been made even though many interfaces can be extended. Some time ago I tested to use QuantConnect.Lean as a git submodule, but ran into some problem with VisualStudio.
